//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter
    {
        public int DemandId { get; set; }
        public Nullable<double> MinArea { get; set; }
        public Nullable<double> MaxArea { get; set; }
        public Nullable<int> MinCoordinateLatitude { get; set; }
        public Nullable<int> MaxCoordinateLatitude { get; set; }
        public Nullable<int> MinCoordinateLongitude { get; set; }
        public Nullable<int> MaxCoordinateLongitude { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public Nullable<int> HouseNum { get; set; }
        public Nullable<int> FlatNum { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public Nullable<decimal> MaxPrice { get; set; }
    
        public virtual Demand Demand { get; set; }
        public virtual FlatFilter FlatFilter { get; set; }
        public virtual HouseFilter HouseFilter { get; set; }
        public virtual LandPlotFilter LandPlotFilter { get; set; }
    }
}
