//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam2
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseFilter
    {
        public int DemandId { get; set; }
        public Nullable<int> MinFloorCount { get; set; }
        public Nullable<int> MaxFloorCount { get; set; }
        public Nullable<int> MinRoomCount { get; set; }
        public Nullable<int> MaxRoomCount { get; set; }
    
        public virtual Filter Filter { get; set; }
    }
}
