//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RealEstateAgencyEntities : DbContext
    {
        static private RealEstateAgencyEntities _context;
        public RealEstateAgencyEntities()
            : base("name=RealEstateAgencyEntities")
        {
        }
    
        static public RealEstateAgencyEntities GetContext()
        {
            if (_context == null)
                _context = new RealEstateAgencyEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Deal> Deal { get; set; }
        public virtual DbSet<Demand> Demand { get; set; }
        public virtual DbSet<Estate> Estate { get; set; }
        public virtual DbSet<Filter> Filter { get; set; }
        public virtual DbSet<Flat> Flat { get; set; }
        public virtual DbSet<FlatFilter> FlatFilter { get; set; }
        public virtual DbSet<House> House { get; set; }
        public virtual DbSet<HouseFilter> HouseFilter { get; set; }
        public virtual DbSet<LandPlot> LandPlot { get; set; }
        public virtual DbSet<LandPlotFilter> LandPlotFilter { get; set; }
        public virtual DbSet<Realtor> Realtor { get; set; }
        public virtual DbSet<Supply> Supply { get; set; }
    }
}
